name: Docs Sync

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**.md"
      - "README.md"
      - ".github/workflows/docs-sync.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "docs/**.md"
      - "README.md"

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install doc tools
        run: |
          npm --version
          npm init -y >/dev/null 2>&1 || true
          npm i -D markdownlint-cli doctoc

      - name: Lint Markdown
        run: npx markdownlint "**/*.md" --ignore node_modules

      - name: Add/refresh TOCs (Doctoc)
        run: |
          # Add or refresh TOC headers inside every docs/*.md (skips node_modules)
          shopt -s globstar
          for f in docs/**/*.md README.md; do
            [ -f "$f" ] || continue
            npx doctoc "$f" --github --notitle --maxlevel 3
          done

      - name: Rebuild docs index
        shell: bash
        run: |
          cat > docs/README.md <<'EOF'
# Animecraft RPG — Docs Index

<!-- auto-generated by docs-sync action; do not edit by hand -->

Below is an auto-generated index of the documentation in this folder.

## Guides & APIs
EOF

          # List immediate children
          while IFS= read -r f; do
            # skip this index file
            [ "$(basename "$f")" = "README.md" ] && continue
            title=$(head -n 1 "$f" | sed 's/^#\s*//; s/^<!--.*-->//')
            [ -z "$title" ] && title="$(basename "$f")"
            echo "- [${title}]($(basename "$f"))" >> docs/README.md
          done < <(find docs -maxdepth 1 -type f -name "*.md" | sort)

          echo "" >> docs/README.md
          echo "## Subfolders" >> docs/README.md
          while IFS= read -r d; do
            base=$(basename "$d")
            echo "- \`$base/\`" >> docs/README.md
          done < <(find docs -mindepth 1 -maxdepth 1 -type d | sort)

      - name: Commit changes (if any)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(docs): lint, TOC refresh, and index rebuild"
          else
            echo "No doc changes to commit."
          fi

      - name: Open pull request if changes exist
        if: ${{ always() }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(docs): lint, TOC refresh, and index rebuild"
          title: "Docs sync: lint, TOC + index"
          body: "Automated docs maintenance."
          branch: docs/sync
          delete-branch: true
